apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-stmd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-stmd
    app.kubernetes.io/part-of: load-app-37be1243-2a26-474d-9ff7-85cfd356b375
  name: devfile-sample-stmd
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-stmd
status:
  loadBalancer: {}
